### PR TITLE
template tag error staticfiles

### PR DESCRIPTION
**Pull request by akashjadhav3**
# What is the purpose of your *pull request*?

 - Staticfiles load tag Bug fix

# Proposed changes
Fixed staticfiles' is not a registered tag library.

### CODE REVIEW

**Review by jackkinsella — APPROVED** [review]
I don't have the capacity to test this right now, but this change looks like the way things should be based on the Django docs and deprecation notices.

What I don't understand is why our team is able to use this fork as it stands (with the old `staticfiles` loaded) without issue. Maybe it's a soft deprecation?

**Comment by jackkinsella** [comment]
And btw super cool that you contributed! Thanks @akashjadhav3

**Comment by jackkinsella** [comment]
We're actually selling this error in production in our admin area today. Gonna merge here and see if fixes things. Will bump version tag to v0.22

**Comment by ecakashjadhav** [comment]
Thanks :)

**Pull request merged**
